name: rust-g
on:
  push:
    branches:
      - master
      - just-so-this-compiles
  pull_request:
    branches:
      - master
      - just-so-this-compiles
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-pc-windows-msvc
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Build (release) (default features)
        run: cargo build -Z build-std --target i686-win7-windows-msvc --locked --release

      - uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: |
            target/i686-win7-windows-msvc/release/rust_g.dll
            target/i686-win7-windows-msvc/release/rust_g.pdb
            target/rust_g.dm
